//! Hot-reload watcher for the plugins directory.
//!
//! Uses the `notify` crate to watch `~/.rtb/plugins/` and automatically
//! start, stop, or restart plugins when their directories or manifests change.

use std::collections::HashSet;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::Duration;

use notify::{Event, EventKind, RecommendedWatcher, RecursiveMode, Watcher};
use tokio::sync::mpsc;
use tracing::{debug, error, info, warn};

use crate::manager::PluginManager;

/// Debounce interval for file-system events to avoid duplicate processing.
const DEBOUNCE_MS: u64 = 500;

/// Events generated by the watcher for the plugin manager.
#[derive(Debug, Clone)]
enum PluginFsEvent {
    /// A new plugin directory with a valid plugin.toml appeared.
    Added(String),
    /// A plugin directory was removed.
    Removed(String),
    /// A plugin.toml was modified.
    Modified(String),
}

/// Watches the plugins directory for changes and auto-starts/stops/restarts plugins.
pub struct PluginWatcher {
    plugins_dir: PathBuf,
    _watcher: RecommendedWatcher,
}

impl PluginWatcher {
    /// Start watching the plugins directory.
    ///
    /// Returns the watcher handle. Dropping it stops watching.
    pub fn start(plugins_dir: PathBuf, manager: Arc<PluginManager>) -> Result<Self, notify::Error> {
        // Ensure the directory exists
        if !plugins_dir.exists() {
            std::fs::create_dir_all(&plugins_dir).map_err(|e| {
                notify::Error::generic(&format!(
                    "failed to create plugins dir {}: {e}",
                    plugins_dir.display()
                ))
            })?;
        }

        let (fs_tx, fs_rx) = mpsc::channel::<PluginFsEvent>(64);
        let dir_clone = plugins_dir.clone();

        // Create the notify watcher with a sync channel bridge to tokio
        let (notify_tx, notify_rx) = std::sync::mpsc::channel::<notify::Result<Event>>();
        let watcher = {
            let tx = notify_tx;
            RecommendedWatcher::new(
                move |res: notify::Result<Event>| {
                    let _ = tx.send(res);
                },
                notify::Config::default().with_poll_interval(Duration::from_secs(2)),
            )?
        };

        // Bridge from sync notify channel to async tokio channel
        let plugins_dir_for_bridge = dir_clone.clone();
        std::thread::spawn(move || {
            // Track known plugin IDs to detect additions/removals
            let mut known_plugins: HashSet<String> = HashSet::new();

            // Initial scan of existing plugins
            if let Ok(entries) = std::fs::read_dir(&plugins_dir_for_bridge) {
                for entry in entries.flatten() {
                    let path = entry.path();
                    if path.is_dir() && path.join("plugin.toml").exists() {
                        if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
                            known_plugins.insert(name.to_string());
                        }
                    }
                }
            }

            while let Ok(event_result) = notify_rx.recv() {
                match event_result {
                    Ok(event) => {
                        let fs_events =
                            classify_event(&event, &plugins_dir_for_bridge, &mut known_plugins);
                        for fs_event in fs_events {
                            if fs_tx.blocking_send(fs_event).is_err() {
                                return; // receiver dropped
                            }
                        }
                    }
                    Err(e) => {
                        warn!(error = %e, "file watcher error");
                    }
                }
            }
        });

        // Spawn the async event processor
        let manager_clone = Arc::clone(&manager);
        tokio::spawn(async move {
            process_fs_events(fs_rx, manager_clone).await;
        });

        // Start watching
        let mut watcher = watcher;
        watcher.watch(plugins_dir.as_ref(), RecursiveMode::Recursive)?;
        info!(dir = %plugins_dir.display(), "watching plugins directory for changes");

        Ok(Self {
            plugins_dir,
            _watcher: watcher,
        })
    }

    /// Returns the watched directory path.
    pub fn plugins_dir(&self) -> &Path {
        &self.plugins_dir
    }
}

/// Classify a notify event into zero or more PluginFsEvents.
fn classify_event(
    event: &Event,
    plugins_dir: &Path,
    known_plugins: &mut HashSet<String>,
) -> Vec<PluginFsEvent> {
    let mut result = Vec::new();

    for path in &event.paths {
        // We only care about plugin.toml files or plugin directories
        let plugin_id = extract_plugin_id(path, plugins_dir);
        let plugin_id = match plugin_id {
            Some(id) => id,
            None => continue,
        };

        let plugin_dir = plugins_dir.join(&plugin_id);
        let manifest_path = plugin_dir.join("plugin.toml");

        match event.kind {
            EventKind::Create(_) => {
                // A file or directory was created
                if manifest_path.exists() && !known_plugins.contains(&plugin_id) {
                    known_plugins.insert(plugin_id.clone());
                    debug!(plugin_id = %plugin_id, "detected new plugin");
                    result.push(PluginFsEvent::Added(plugin_id));
                }
            }
            EventKind::Modify(_) => {
                // A file was modified — check if it's plugin.toml
                if path.file_name().and_then(|n| n.to_str()) == Some("plugin.toml") {
                    if known_plugins.contains(&plugin_id) {
                        debug!(plugin_id = %plugin_id, "detected plugin.toml modification");
                        result.push(PluginFsEvent::Modified(plugin_id));
                    } else if manifest_path.exists() {
                        known_plugins.insert(plugin_id.clone());
                        debug!(plugin_id = %plugin_id, "detected new plugin via modified plugin.toml");
                        result.push(PluginFsEvent::Added(plugin_id));
                    }
                }
            }
            EventKind::Remove(_) => {
                // A file or directory was removed
                if !plugin_dir.exists() && known_plugins.contains(&plugin_id) {
                    known_plugins.remove(&plugin_id);
                    debug!(plugin_id = %plugin_id, "detected plugin removal");
                    result.push(PluginFsEvent::Removed(plugin_id));
                } else if !manifest_path.exists() && known_plugins.contains(&plugin_id) {
                    // plugin.toml was removed but directory still exists
                    known_plugins.remove(&plugin_id);
                    debug!(plugin_id = %plugin_id, "detected plugin.toml removal");
                    result.push(PluginFsEvent::Removed(plugin_id));
                }
            }
            _ => {}
        }
    }

    result
}

/// Extract the plugin ID (directory name) from a file path within the plugins directory.
fn extract_plugin_id(path: &Path, plugins_dir: &Path) -> Option<String> {
    let relative = path.strip_prefix(plugins_dir).ok()?;
    let first_component = relative.components().next()?;
    match first_component {
        std::path::Component::Normal(name) => name.to_str().map(|s| s.to_string()),
        _ => None,
    }
}

/// Process classified file-system events with debouncing.
async fn process_fs_events(mut rx: mpsc::Receiver<PluginFsEvent>, manager: Arc<PluginManager>) {
    // Simple debounce: collect events over a window, then process unique ones
    let debounce = Duration::from_millis(DEBOUNCE_MS);

    loop {
        // Wait for the first event
        let first = match rx.recv().await {
            Some(event) => event,
            None => return,
        };

        let mut events = vec![first];

        // Collect any additional events within the debounce window
        let deadline = tokio::time::sleep(debounce);
        tokio::pin!(deadline);

        loop {
            tokio::select! {
                more = rx.recv() => {
                    match more {
                        Some(event) => events.push(event),
                        None => {
                            process_batch(&events, &manager).await;
                            return;
                        }
                    }
                }
                _ = &mut deadline => {
                    break;
                }
            }
        }

        process_batch(&events, &manager).await;
    }
}

/// Process a debounced batch of events, deduplicating by plugin ID.
async fn process_batch(events: &[PluginFsEvent], manager: &PluginManager) {
    // Deduplicate: keep the last event per plugin ID
    let mut actions: std::collections::HashMap<String, &PluginFsEvent> =
        std::collections::HashMap::new();

    for event in events {
        let id = match event {
            PluginFsEvent::Added(id) | PluginFsEvent::Removed(id) | PluginFsEvent::Modified(id) => {
                id.clone()
            }
        };
        actions.insert(id, event);
    }

    for (plugin_id, event) in actions {
        match event {
            PluginFsEvent::Added(id) => {
                info!(plugin_id = %id, "auto-starting new plugin");
                if let Err(e) = manager.start_plugin_by_id(id).await {
                    error!(plugin_id = %plugin_id, error = %e, "failed to auto-start plugin");
                }
            }
            PluginFsEvent::Removed(id) => {
                info!(plugin_id = %id, "auto-stopping removed plugin");
                if let Err(e) = manager.stop_plugin(id).await {
                    // Not found is fine — might already be stopped
                    debug!(plugin_id = %plugin_id, error = %e, "stop_plugin during removal");
                }
            }
            PluginFsEvent::Modified(id) => {
                info!(plugin_id = %id, "restarting plugin due to manifest change");
                // Stop then start
                let _ = manager.stop_plugin(id).await;
                if let Err(e) = manager.start_plugin_by_id(&plugin_id).await {
                    error!(plugin_id = %plugin_id, error = %e, "failed to restart plugin");
                }
            }
        }
    }
}
